config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/random', to: 'home#random'
end

app/models/country.rb
class Country < OpenStruct
  SOURCE_FILE = 'db/countries.csv'.freeze

  def self.find_by_name(country_name)
    CSV.foreach("#{Rails.root}/#{SOURCE_FILE}", headers: true, header_converters: :symbol) do |row|
      return new(row.to_h) if row[:name] == country_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @weather = OpenWeatherMap::CityFetcher.fetch(params[:country], params[:city])
    flash[:alert] = @weather.errors if search_params.include?(:city)
  end

  def random
    lat = rand(-90.000000000...90.000000000)
    lon = rand(-180.000000000...180.000000000)
    @weather = OpenWeatherMap::CoordsFetcher.fetch(lat, lon)
    render :index
  end

  private

  def search_params
    params.permit(:country, :city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def weather_title(weather)
    title = 'Weather for '

    if weather.try(:city)
      title += weather.city
      title += ", #{weather.country.name}" if weather.country
    else
      title += @weather.raw_data['name']
    end

    title
  end

  def time_from_timestamp(time_s)
    Time.strptime(time_s, '%s').strftime('at %I:%M%p')
  end
end

app/views/home/index.html.slim
h1 Open Weather App

=form_tag(root_path, method: :get, class: 'form-inline')
  input#inlineFormInput.form-control.mb-2.mr-sm-2.mb-sm-0 type="text" name="country" placeholder="Country"
  input#inlineFormInput.form-control.mb-2.mr-sm-2.mb-sm-0 type="text" name="city" placeholder="City"
  button.btn.btn-primary type="submit" Submit
br
=form_tag(random_path, method: :get, class: 'form-inline')
  button.btn.btn-primary.btn-lg type="submit" Random

.container#weather
  - if @weather && @weather.valid?
    h2
      = weather_title(@weather)
    br
    div
      h4 #{@weather.raw_data['weather'].first['main']} (#{@weather.raw_data['weather'].first['description']})
      h4 Weather:
      ul
        li Temperature: #{@weather.raw_data['main']['temp']} Celsius
        li Temperature min: #{@weather.raw_data['main']['temp_min']} Celsius
        li Temperature max: #{@weather.raw_data['main']['temp_max']} Celsius
        li Humidity: #{@weather.raw_data['main']['humidity']}%
        li Pressure: #{@weather.raw_data['main']['pressure']} hPa
        li Visibility: #{@weather.raw_data['visibility']} meters
        li Wind speed: #{@weather.raw_data['wind']['speed']} meter/sec
        - if @weather.raw_data['clouds']
          li Clouds: #{@weather.raw_data['clouds']['all']}%
        - if @weather.raw_data['rain']
          li Rain: #{@weather.raw_data['rain']['rain.3h']}
        - if @weather.raw_data['snow']
          li Snow: #{@weather.raw_data['snow']['snow.3h']}
      h4 Coordinates:
      ul
        li latitude: #{@weather.raw_data['coord']['lat']}
        li longitude: #{@weather.raw_data['coord']['lon']}

      h4 Sys
      ul
        li Sunrise: #{time_from_timestamp(@weather.raw_data['sys']['sunrise'].to_s)}
        li Sunset: #{time_from_timestamp(@weather.raw_data['sys']['sunset'].to_s)}

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "OpenWeatherApp"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"]
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand[href="#"]
          | OpenWeatherApp
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      footer
        p
          | © OpenWeatherApp 2018